#!/usr/bin/env python3
"""Export backend-owned reference data into typed JSON for the console.

WHY THIS EXISTS
---------------
Several things the console must show correctly are backend SOURCE OF TRUTH with
no HTTP surface: the protocol support matrix, the three separate known-limitation
registers, the PaymentIntent transition table, and the kernel's own enums. Phase 9
is a frontend phase, so no endpoint was invented to serve them.

Re-typing those values into TypeScript by hand is the exact failure
``services/adapters/support.py`` was written to prevent — a claim in one file
drifting away from the code in another. So they are IMPORTED from the real
modules and serialized. The console renders generated data; nobody authors it.

WHAT IT DELIBERATELY DOES NOT EXPORT
------------------------------------
No measured metric, no run result, no count of anything that happened. Those are
either live API reads or a labelled benchmark report. This file exports only
declarations — what the system SAYS about itself in its own source.

Run from the repository root:

    python3 apps/web/scripts/export_reference.py

or from apps/web:

    npm run export-reference
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve()
WEB_ROOT = HERE.parent.parent
REPO_ROOT = WEB_ROOT.parent.parent
OUT_DIR = WEB_ROOT / "src" / "data"

sys.path.insert(0, str(REPO_ROOT))

from packages.schemas.capability import Capability  # noqa: E402
from packages.schemas.domain import (  # noqa: E402
    EventType,
    MissionState,
    PolicyOutcome,
    ReasonCode,
)
from packages.schemas.payment import (  # noqa: E402
    TERMINAL_PAYMENT_STATES,
    UNCERTAIN_PAYMENT_STATES,
    PaymentIntentState,
)
from packages.schemas.provenance import AuthorityLevel, TrustLevel  # noqa: E402
from services.adapters.limitations import ADAPTER_LIMITATIONS  # noqa: E402
from services.adapters.models import AdapterFamily, AdapterWarningCode  # noqa: E402
from services.adapters.support import PROTOCOL_SUPPORT  # noqa: E402
from services.attack_lab.limitations import KNOWN_LIMITATIONS  # noqa: E402
from services.attack_lab.models import (  # noqa: E402
    MALICIOUS_CATEGORIES,
    AttackCategory,
    AttackStatus,
    Severity,
)
from services.audit_ledger.verify import AuditReasonCode  # noqa: E402
from services.payment_executor.state_machine import (  # noqa: E402
    ALLOWED_PAYMENT_TRANSITIONS,
)
from services.risk_engine.limitations import RISK_LIMITATIONS  # noqa: E402
from services.risk_engine.models import RiskBand, RiskRecommendation  # noqa: E402

BANNER = (
    "GENERATED by apps/web/scripts/export_reference.py from backend source. "
    "Do not edit by hand — regenerate with `npm run export-reference`."
)


def _limitations(register: Any) -> list[dict[str, Any]]:
    return [
        {
            "id": item.id,
            "title": item.title,
            "detail": item.detail,
            "demonstratedBy": item.demonstrated_by,
        }
        for item in register
    ]


def _invariant_contract() -> list[str]:
    """The test contract, parsed from the README block that publishes it.

    Parsed rather than copied so the console cannot claim an invariant the
    README does not, and so a contract change shows up here as a diff.
    """
    readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
    match = re.search(
        r"## Critical invariants \(the test contract\)\s*\n+```text\n(.*?)```",
        readme,
        re.DOTALL,
    )
    if match is None:  # pragma: no cover - the heading is stable
        raise SystemExit("could not locate the invariant contract block in README.md")
    return [line.strip() for line in match.group(1).splitlines() if line.strip()]


def build() -> dict[str, Any]:
    return {
        "protocolSupport": {
            "_generated": BANNER,
            "_source": "services/adapters/support.py :: PROTOCOL_SUPPORT",
            "entries": [
                {
                    "protocol": e.protocol,
                    "actualRole": e.actual_role,
                    "family": e.family.value if e.family is not None else None,
                    "status": e.status.value,
                    "adapterId": e.adapter_id,
                    "supported": e.supported,
                    "notSupported": e.not_supported,
                    "reason": e.reason,
                    "specificationSources": list(e.specification_sources),
                }
                for e in PROTOCOL_SUPPORT
            ],
        },
        "limitations": {
            "_generated": BANNER,
            "_source": (
                "services/attack_lab/limitations.py, services/risk_engine/limitations.py, "
                "services/adapters/limitations.py"
            ),
            "security": _limitations(KNOWN_LIMITATIONS),
            "risk": _limitations(RISK_LIMITATIONS),
            "adapter": _limitations(ADAPTER_LIMITATIONS),
        },
        "paymentStateMachine": {
            "_generated": BANNER,
            "_source": "services/payment_executor/state_machine.py :: ALLOWED_PAYMENT_TRANSITIONS",
            "states": [s.value for s in PaymentIntentState],
            "transitions": {
                state.value: sorted(t.value for t in targets)
                for state, targets in ALLOWED_PAYMENT_TRANSITIONS.items()
            },
            "terminal": sorted(s.value for s in TERMINAL_PAYMENT_STATES),
            "uncertain": sorted(s.value for s in UNCERTAIN_PAYMENT_STATES),
        },
        "vocabulary": {
            "_generated": BANNER,
            "_source": "packages/schemas/*, services/attack_lab/models.py, services/risk_engine/models.py",
            "invariantContract": _invariant_contract(),
            "missionStates": [s.value for s in MissionState],
            "eventTypes": [e.value for e in EventType],
            "policyOutcomes": [p.value for p in PolicyOutcome],
            "reasonCodes": [r.value for r in ReasonCode],
            "auditReasonCodes": [a.value for a in AuditReasonCode],
            "authorityLevels": [
                {"name": a.name, "value": int(a.value)} for a in sorted(AuthorityLevel)
            ],
            "trustLevels": [t.value for t in TrustLevel],
            "capabilities": [c.value for c in Capability],
            "attackCategories": [c.value for c in AttackCategory],
            "maliciousCategories": sorted(c.value for c in MALICIOUS_CATEGORIES),
            "attackStatuses": [s.value for s in AttackStatus],
            "severities": [s.value for s in Severity],
            "riskBands": [b.value for b in RiskBand],
            "riskRecommendations": [r.value for r in RiskRecommendation],
            "adapterFamilies": [f.value for f in AdapterFamily],
            "adapterWarningCodes": [w.value for w in AdapterWarningCode],
        },
    }


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, payload in build().items():
        target = OUT_DIR / f"{name}.generated.json"
        target.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"wrote {target.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
