import type { DecisionTraceEntry } from "@/lib/types/pactra";

export interface DemoTraceScenario {
  id: string;
  name: string;
  category: "STANDARD" | "APPROVAL" | "RELIABILITY" | "SECURITY";
  description: string;
  provenance: {
    origin: string;
    trustClassification: string;
    authorityPath: string;
  };
  decisionTrace: DecisionTraceEntry[];
}

export const AUDIT_DEMO_SCENARIOS: Record<string, DemoTraceScenario> = {
  BENIGN_PURCHASE: {
    id: "BENIGN_PURCHASE",
    name: "1. Benign Autonomous Purchase",
    category: "STANDARD",
    description: "Standard end-to-end autonomous transaction within soft budget policy. Policy auto-authorized; payment succeeded.",
    provenance: {
      origin: "AI Buyer Assistant -> TechCorp Offer Catalog",
      trustClassification: "UNTRUSTED MERCHANT PROPOSAL -> RE-BOUND AUTHORITATIVE TRANSACTION",
      authorityPath: "Deterministic Policy Auto-Approval (POLICY_AUTO)",
    },
    decisionTrace: [
      {
        stage: "ADMIT",
        event_type: "POLICY_DECISION",
        verdict: "ACCEPTED",
        reason_codes: ["WITHIN_LIMITS"],
        invariant_id: null,
        approval_scheme: "POLICY_AUTO",
        policy_outcome: "ALLOW",
        payment_state: "CREATED",
        advisory: false,
        next_action: "CONTINUE_BIND",
        evidence: { event_id: "evt_audit_demo_01", sequence: 1, actor: "security_kernel" },
        recorded_at: "2026-09-01T16:00:00.000Z",
      },
      {
        stage: "BIND",
        event_type: "AUTHORIZATION_CREATED",
        verdict: "ACCEPTED",
        reason_codes: ["WITHIN_LIMITS"],
        invariant_id: null,
        approval_scheme: "POLICY_AUTO",
        policy_outcome: "ALLOW",
        payment_state: "QUEUED",
        advisory: false,
        next_action: "DISPATCH_PAYMENT",
        evidence: { event_id: "evt_audit_demo_02", sequence: 2, actor: "security_kernel" },
        recorded_at: "2026-09-01T16:00:01.000Z",
      },
      {
        stage: "EXECUTE",
        event_type: "PAYMENT_ATTEMPTED",
        verdict: "PENDING",
        reason_codes: [],
        invariant_id: null,
        approval_scheme: "POLICY_AUTO",
        policy_outcome: "ALLOW",
        payment_state: "PROCESSING",
        advisory: false,
        next_action: "AWAIT_PROVIDER",
        evidence: { event_id: "evt_audit_demo_03", sequence: 3, actor: "payment_executor" },
        recorded_at: "2026-09-01T16:00:02.000Z",
      },
      {
        stage: "EXECUTE",
        event_type: "PAYMENT_SUCCEEDED",
        verdict: "SUCCEEDED",
        reason_codes: [],
        invariant_id: null,
        approval_scheme: "POLICY_AUTO",
        policy_outcome: "ALLOW",
        payment_state: "SUCCEEDED",
        advisory: false,
        next_action: "NONE",
        evidence: { event_id: "evt_audit_demo_04", sequence: 4, actor: "payment_executor" },
        recorded_at: "2026-09-01T16:00:05.000Z",
      },
    ],
  },

  USER_APPROVAL_FLOW: {
    id: "USER_APPROVAL_FLOW",
    name: "2. Budget Threshold Approval Required",
    category: "APPROVAL",
    description: "Transaction amount exceeds soft budget limit. Policy outcome is REQUIRE_APPROVAL; awaiting Ed25519 user approval signature.",
    provenance: {
      origin: "AI Buyer Assistant -> ProGear Audio Offer",
      trustClassification: "UNTRUSTED PROPOSAL -> POLICY REQUIRE_APPROVAL",
      authorityPath: "Explicit User Cryptographic Signature (USER_ED25519)",
    },
    decisionTrace: [
      {
        stage: "ADMIT",
        event_type: "POLICY_DECISION",
        verdict: "ACCEPTED",
        reason_codes: ["SOFT_BUDGET_EXCEEDED"],
        invariant_id: null,
        approval_scheme: "USER_ED25519",
        policy_outcome: "REQUIRE_APPROVAL",
        payment_state: "CREATED",
        advisory: false,
        next_action: "CONTINUE_BIND",
        evidence: { event_id: "evt_audit_appr_01", sequence: 1, actor: "security_kernel" },
        recorded_at: "2026-09-01T16:05:00.000Z",
      },
      {
        stage: "BIND",
        event_type: "AUTHORIZATION_CREATED",
        verdict: "ACCEPTED",
        reason_codes: ["SOFT_BUDGET_EXCEEDED"],
        invariant_id: null,
        approval_scheme: "USER_ED25519",
        policy_outcome: "REQUIRE_APPROVAL",
        payment_state: "QUEUED",
        advisory: false,
        next_action: "AWAIT_USER_SIGNATURE",
        evidence: { event_id: "evt_audit_appr_02", sequence: 2, actor: "security_kernel" },
        recorded_at: "2026-09-01T16:05:01.000Z",
      },
      {
        stage: "BIND",
        event_type: "APPROVAL_REQUESTED",
        verdict: "PENDING",
        reason_codes: ["SOFT_BUDGET_EXCEEDED"],
        invariant_id: null,
        approval_scheme: "USER_ED25519",
        policy_outcome: "REQUIRE_APPROVAL",
        payment_state: "QUEUED",
        advisory: false,
        next_action: "AWAIT_USER_SIGNATURE",
        evidence: { event_id: "evt_audit_appr_03", sequence: 3, actor: "security_kernel" },
        recorded_at: "2026-09-01T16:05:02.000Z",
      },
    ],
  },

  LOST_PROVIDER_RESPONSE: {
    id: "LOST_PROVIDER_RESPONSE",
    name: "3. Lost Provider Response (Reliability)",
    category: "RELIABILITY",
    description: "Provider gateway timeout during payment dispatch. PACTRA records uncertainty (PROVIDER_PENDING) and schedules reconciliation.",
    provenance: {
      origin: "Payment Gateway Outbox -> Provider Network Boundary",
      trustClassification: "PROVIDER NETWORK UNCERTAINTY",
      authorityPath: "Automated Evidence Reconciliation (RECONCILE_PAYMENT)",
    },
    decisionTrace: [
      {
        stage: "ADMIT",
        event_type: "POLICY_DECISION",
        verdict: "ACCEPTED",
        reason_codes: ["WITHIN_LIMITS"],
        invariant_id: null,
        approval_scheme: "POLICY_AUTO",
        policy_outcome: "ALLOW",
        payment_state: "CREATED",
        advisory: false,
        next_action: "CONTINUE_BIND",
        evidence: { event_id: "evt_audit_lost_01", sequence: 1, actor: "security_kernel" },
        recorded_at: "2026-09-01T16:10:00.000Z",
      },
      {
        stage: "BIND",
        event_type: "AUTHORIZATION_CREATED",
        verdict: "ACCEPTED",
        reason_codes: ["WITHIN_LIMITS"],
        invariant_id: null,
        approval_scheme: "POLICY_AUTO",
        policy_outcome: "ALLOW",
        payment_state: "QUEUED",
        advisory: false,
        next_action: "DISPATCH_PAYMENT",
        evidence: { event_id: "evt_audit_lost_02", sequence: 2, actor: "security_kernel" },
        recorded_at: "2026-09-01T16:10:01.000Z",
      },
      {
        stage: "EXECUTE",
        event_type: "PAYMENT_ATTEMPTED",
        verdict: "PENDING",
        reason_codes: [],
        invariant_id: null,
        approval_scheme: "POLICY_AUTO",
        policy_outcome: "ALLOW",
        payment_state: "PROCESSING",
        advisory: false,
        next_action: "AWAIT_PROVIDER",
        evidence: { event_id: "evt_audit_lost_03", sequence: 3, actor: "payment_executor" },
        recorded_at: "2026-09-01T16:10:02.000Z",
      },
      {
        stage: "EXECUTE",
        event_type: "PAYMENT_PROVIDER_TIMEOUT",
        verdict: "PENDING",
        reason_codes: ["PAYMENT_PROVIDER_TIMEOUT"],
        invariant_id: null,
        approval_scheme: "POLICY_AUTO",
        policy_outcome: "ALLOW",
        payment_state: "PROVIDER_PENDING",
        advisory: false,
        next_action: "RECONCILE_PAYMENT",
        evidence: { event_id: "evt_audit_lost_04", sequence: 4, actor: "payment_executor" },
        recorded_at: "2026-09-01T16:10:15.000Z",
      },
    ],
  },

  POST_AUTH_MUTATION: {
    id: "POST_AUTH_MUTATION",
    name: "4. Post-Authorization Mutation Refusal",
    category: "SECURITY",
    description: "Tampering attempted after authorization issued. Canonical digest mismatch invalidates authorization before payment dispatch.",
    provenance: {
      origin: "Adversarial Ingress -> Digest Verification Gate",
      trustClassification: "TAMPERED TRANSACTION TERMS PRESENTED",
      authorityPath: "Deterministic Binding Re-Verification Check",
    },
    decisionTrace: [
      {
        stage: "ADMIT",
        event_type: "POLICY_DECISION",
        verdict: "ACCEPTED",
        reason_codes: ["WITHIN_LIMITS"],
        invariant_id: null,
        approval_scheme: "POLICY_AUTO",
        policy_outcome: "ALLOW",
        payment_state: "CREATED",
        advisory: false,
        next_action: "CONTINUE_BIND",
        evidence: { event_id: "evt_audit_mut_01", sequence: 1, actor: "security_kernel" },
        recorded_at: "2026-09-01T16:15:00.000Z",
      },
      {
        stage: "BIND",
        event_type: "AUTHORIZATION_CREATED",
        verdict: "ACCEPTED",
        reason_codes: ["WITHIN_LIMITS"],
        invariant_id: null,
        approval_scheme: "POLICY_AUTO",
        policy_outcome: "ALLOW",
        payment_state: "QUEUED",
        advisory: false,
        next_action: "DISPATCH_PAYMENT",
        evidence: { event_id: "evt_audit_mut_02", sequence: 2, actor: "security_kernel" },
        recorded_at: "2026-09-01T16:15:01.000Z",
      },
      {
        stage: "BIND",
        event_type: "TRANSACTION_BINDING_FAILURE",
        verdict: "REFUSED",
        reason_codes: ["TRANSACTION_BINDING_FAILURE"],
        invariant_id: null,
        approval_scheme: "POLICY_AUTO",
        policy_outcome: "DENY",
        payment_state: "FAILED_TERMINAL",
        advisory: false,
        next_action: "NONE",
        evidence: { event_id: "evt_audit_mut_03", sequence: 3, actor: "security_kernel" },
        recorded_at: "2026-09-01T16:15:02.000Z",
      },
    ],
  },
};
